[workspace]
resolver = "2"
members = [
    "diet-mac-and-cheese",
    "fancy-garbling",
    "fancy-garbling/base_conversion",
    "humidor",
    "inferno",
    "keyed_arena",
    "ocelot",
    "popsicle",
    "scuttlebutt",
    "simple-arith-circuit",
    "vectoreyes",
]

[workspace.package]
authors = ["swanky authors <swanky@galois.com>"]
license = "MIT"
edition = "2021"
publish = false
version = "0.5.0"

[workspace.dependencies]
# Our crates
fancy-garbling = { path = "fancy-garbling" }
fancy-garbling-base-conversion = { path = "fancy-garbling/base_conversion" }
humidor = { path = "humidor" }
keyed_arena = { path = "keyed_arena" }
ocelot = { path = "ocelot" }
popsicle = { path = "popsicle" }
scuttlebutt = { path = "scuttlebutt" }
simple-arith-circuit = { path = "simple-arith-circuit" }
vectoreyes = { path = "vectoreyes" }

# Patched Dependencies
ff = { git = "https://github.com/GaloisInc/ff", rev = "b8d8570f67d04cf5a8b82df3d6eb36aeb4732e92" }
ff_codegen = { git = "https://github.com/GaloisInc/ff", rev = "b8d8570f67d04cf5a8b82df3d6eb36aeb4732e92" }
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4.1.1" }

# External Dependencies
aes = "0.8.2"
anyhow = "1.0.65"
bincode = "1.3.3"
blake3 = "1.3.3"
bumpalo = "3.11.1"
bytemuck = "1.12.3"
cc = "1.0.77"
clap = "4.0.29"
criterion = "0.4.0"
crossbeam-queue = "0.3.8"
digest = "0.10.6"
generic-array = "0.14.6"
hex = "0.4.3"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
merkle-cbt = "0.3.2"
ndarray = "0.15.6"
nix = "0.26.1"
num-bigint = "0.4.3"
num-traits = "0.2.15"
openssl = "0.10.43"
parking_lot = "0.12.1"
pretty_env_logger = "0.4"
proptest = "1.0.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
rayon = "1.5.3"
regex = "1.7.0"
serde = "1.0.148"
serde_json = "1.0.89"
sha2 = "0.10.6"
simple_logger = "2.1.0"
smallvec = "1.10.0"
snafu = "0.7.1"
sprs = "0.11.0"
subtle = "2.4.1"
tempfile = "3.3.0"
zki_sieve = { git = "https://github.com/QED-it/zkinterface-ir.git", rev = "3368622bdf5306256e56826141517a3a34f8f85c"}

uds_windows = "1.1.0"

[profile.release]
opt-level = 3
debug = true
lto = true
debug-assertions = false
overflow-checks = false
codegen-units = 1

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = true
lto = true
debug-assertions = false
overflow-checks = false

[profile.test]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
